//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/Gilbo Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GilboInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GilboInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Gilbo Input"",
    ""maps"": [
        {
            ""name"": ""In Car"",
            ""id"": ""09ae7a8c-f7d7-4c81-a6d3-c91c6d39faa6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8399ed42-3dfa-4646-ab7f-3a54e0edd3ec"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""534eebc6-446d-415e-b268-48657d789548"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""fffa1457-d986-41a7-ae7c-b2bb39bd31da"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Abilities"",
                    ""type"": ""Button"",
                    ""id"": ""80baae31-a5e0-4ec8-ad47-9a642fc9691b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Forward"",
                    ""id"": ""3a795e96-08e9-4870-b218-f1f1105b89fa"",
                    ""path"": ""1DAxis(minValue=0,whichSideWins=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""451812d2-1087-424e-b636-2e8e047b1965"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Back"",
                    ""id"": ""c42ff5ad-7da6-49a1-97c0-0c914f2254c1"",
                    ""path"": ""1DAxis(maxValue=0,whichSideWins=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d4d48fc7-3f9d-4b2a-804c-dd810171deeb"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""78fad568-401f-4ad5-b561-19bf654aa30d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2f85f3b3-052b-4ef4-8a54-5f1e9714226b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3db75884-7557-4499-9a84-301c59054a82"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9577e184-5fcb-4a50-806c-8aee0b78a52a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8ca21ece-5fab-4651-96c2-754da896c1b1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abilities"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""GamePad"",
            ""bindingGroup"": ""GamePad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // In Car
        m_InCar = asset.FindActionMap("In Car", throwIfNotFound: true);
        m_InCar_Move = m_InCar.FindAction("Move", throwIfNotFound: true);
        m_InCar_Shoot = m_InCar.FindAction("Shoot", throwIfNotFound: true);
        m_InCar_Aim = m_InCar.FindAction("Aim", throwIfNotFound: true);
        m_InCar_Abilities = m_InCar.FindAction("Abilities", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // In Car
    private readonly InputActionMap m_InCar;
    private List<IInCarActions> m_InCarActionsCallbackInterfaces = new List<IInCarActions>();
    private readonly InputAction m_InCar_Move;
    private readonly InputAction m_InCar_Shoot;
    private readonly InputAction m_InCar_Aim;
    private readonly InputAction m_InCar_Abilities;
    public struct InCarActions
    {
        private @GilboInput m_Wrapper;
        public InCarActions(@GilboInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_InCar_Move;
        public InputAction @Shoot => m_Wrapper.m_InCar_Shoot;
        public InputAction @Aim => m_Wrapper.m_InCar_Aim;
        public InputAction @Abilities => m_Wrapper.m_InCar_Abilities;
        public InputActionMap Get() { return m_Wrapper.m_InCar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InCarActions set) { return set.Get(); }
        public void AddCallbacks(IInCarActions instance)
        {
            if (instance == null || m_Wrapper.m_InCarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InCarActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @Abilities.started += instance.OnAbilities;
            @Abilities.performed += instance.OnAbilities;
            @Abilities.canceled += instance.OnAbilities;
        }

        private void UnregisterCallbacks(IInCarActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @Abilities.started -= instance.OnAbilities;
            @Abilities.performed -= instance.OnAbilities;
            @Abilities.canceled -= instance.OnAbilities;
        }

        public void RemoveCallbacks(IInCarActions instance)
        {
            if (m_Wrapper.m_InCarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInCarActions instance)
        {
            foreach (var item in m_Wrapper.m_InCarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InCarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InCarActions @InCar => new InCarActions(this);
    private int m_GamePadSchemeIndex = -1;
    public InputControlScheme GamePadScheme
    {
        get
        {
            if (m_GamePadSchemeIndex == -1) m_GamePadSchemeIndex = asset.FindControlSchemeIndex("GamePad");
            return asset.controlSchemes[m_GamePadSchemeIndex];
        }
    }
    public interface IInCarActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnAbilities(InputAction.CallbackContext context);
    }
}
